import type { Avatar, Palette, Style, CategoryName } from './types'

/* ===== 分类 ===== */
export const CATEGORY_NAMES: readonly CategoryName[] = Object.freeze([
  '餐饮', '交通', '购物', '娱乐', '医疗', '固定账单', '其他',
])

export const CATEGORY_ALIASES: Record<string, CategoryName> = Object.freeze({
  food: '餐饮', transport: '交通', shop: '购物', shopping: '购物',
  entertainment: '娱乐', health: '医疗', medical: '医疗', bills: '固定账单', other: '其他',
})

/* ===== 头像库 ===== */
export const AVATAR_LIBRARY: readonly Avatar[] = Object.freeze([
  { id: 'orange-cat', name: '小橘猫', fallback: '<svg width="100%" height="100%" viewBox="0 0 80 80" role="img" aria-label="小橘猫头像"><rect width="80" height="80" rx="18" fill="#FFE3B3"/><path d="M18 31 16 13l16 10c5-2 11-2 16 0l16-10-2 18c3 5 4 11 2 17-4 12-14 18-26 18S24 60 20 48c-2-6-1-12 2-17Z" fill="#F28C28" stroke="#8C4A16" stroke-width="2.5" stroke-linejoin="round"/><circle cx="31" cy="43" r="3" fill="#222"/><circle cx="49" cy="43" r="3" fill="#222"/><path d="M37 52q3 3 6 0M24 39l7-3M56 39l-7-3" fill="none" stroke="#222" stroke-width="2.5" stroke-linecap="round"/></svg>' },
  { id: 'blueberry-rabbit', name: '蓝莓兔', fallback: '<svg width="100%" height="100%" viewBox="0 0 80 80" role="img" aria-label="蓝莓兔头像"><rect width="80" height="80" rx="18" fill="#DDEBFF"/><path d="M25 28C15 15 20 7 27 10l8 13c4-2 9-2 13 0l8-13c7-3 12 5 2 18 4 5 5 12 2 20-4 10-13 15-22 15S20 48 18 38c-1-4 1-7 7-10Z" fill="#78A9FF" stroke="#315BBD" stroke-width="2.5" stroke-linejoin="round"/><circle cx="31" cy="41" r="3" fill="#173A7A"/><circle cx="49" cy="41" r="3" fill="#173A7A"/><path d="M37 50h6M40 48v5" stroke="#173A7A" stroke-width="2.5" stroke-linecap="round"/></svg>' },
  { id: 'energy-bear', name: '元气熊', fallback: '<svg width="100%" height="100%" viewBox="0 0 80 80" role="img" aria-label="元气熊头像"><rect width="80" height="80" rx="18" fill="#FFF1B8"/><circle cx="24" cy="25" r="10" fill="#B97843" stroke="#70431F" stroke-width="2.5"/><circle cx="56" cy="25" r="10" fill="#B97843" stroke="#70431F" stroke-width="2.5"/><circle cx="40" cy="43" r="25" fill="#D99A5B" stroke="#70431F" stroke-width="2.5"/><circle cx="32" cy="41" r="3" fill="#222"/><circle cx="48" cy="41" r="3" fill="#222"/><ellipse cx="40" cy="51" rx="8" ry="6" fill="#FFE6C5"/><path d="M37 51q3 3 6 0" fill="none" stroke="#70431F" stroke-width="2" stroke-linecap="round"/></svg>' },
  { id: 'happy-fox', name: '开心狐', fallback: '<svg width="100%" height="100%" viewBox="0 0 80 80" role="img" aria-label="开心狐头像"><rect width="80" height="80" rx="18" fill="#FFE0D2"/><path d="M16 22 22 9l18 11L58 9l6 13c2 5 1 14-3 21-5 9-12 14-21 14S24 52 19 43c-4-7-5-16-3-21Z" fill="#F06F4F" stroke="#9F3522" stroke-width="2.5" stroke-linejoin="round"/><path d="M22 28q18 12 36 0v16c-6 10-30 10-36 0Z" fill="#FFF6EA"/><circle cx="31" cy="37" r="3" fill="#222"/><circle cx="49" cy="37" r="3" fill="#222"/><path d="M35 47q5 5 10 0" fill="none" stroke="#9F3522" stroke-width="2.5" stroke-linecap="round"/></svg>' },
  { id: 'cloud-buddy', name: '云朵仔', fallback: '<svg width="100%" height="100%" viewBox="0 0 80 80" role="img" aria-label="云朵仔头像"><rect width="80" height="80" rx="18" fill="#E8F7F2"/><path d="M18 51c-7-12 3-21 13-19 3-12 22-14 27-1 12-2 18 13 9 21-5 5-15 5-24 5-10 0-20 0-25-6Z" fill="#FFFFFF" stroke="#55B89A" stroke-width="2.5"/><circle cx="32" cy="42" r="3" fill="#245B50"/><circle cx="49" cy="42" r="3" fill="#245B50"/><path d="M37 50q4 3 8 0" fill="none" stroke="#245B50" stroke-width="2.5" stroke-linecap="round"/></svg>' },
  { id: 'rainbow-bird', name: '彩虹鸟', fallback: '<svg width="100%" height="100%" viewBox="0 0 80 80" role="img" aria-label="彩虹鸟头像"><rect width="80" height="80" rx="18" fill="#E8DEFF"/><path d="M18 47c0-16 10-27 25-27 10 0 19 6 22 16l-11 1 7 9-14 1 2 11H31c-8 0-13-4-13-11Z" fill="#8559D6" stroke="#4A2C96" stroke-width="2.5" stroke-linejoin="round"/><path d="M28 31c6-8 16-9 23-3" fill="none" stroke="#F2C94C" stroke-width="4" stroke-linecap="round"/><circle cx="48" cy="35" r="3" fill="#222"/><path d="M64 40h8M64 46h8" stroke="#4A2C96" stroke-width="2.5" stroke-linecap="round"/></svg>' },
])

/* ===== 调色板 ===== */
export const PALETTES: readonly Palette[] = Object.freeze([
  { id: 'default',  name: '浅蓝',   primary: '#0066ff' },
  { id: 'ocean',    name: '海洋',   primary: '#0369a1' },
  { id: 'midnight', name: '暗夜',   primary: '#818cf8' },
  { id: 'warm',     name: '暖米',   primary: '#d97706' },
  { id: 'mint',     name: '薄荷',   primary: '#059669' },
  { id: 'rose',     name: '玫瑰',   primary: '#be185d' },
  { id: 'lavender', name: '薰衣草', primary: '#7c3aed' },
  { id: 'forest',   name: '森林',   primary: '#15803d' },
  { id: 'cherry',   name: '樱桃',   primary: '#be123c' },
  { id: 'gold',     name: '琥珀',   primary: '#a16207' },
  { id: 'coral',    name: '珊瑚',   primary: '#e8590c' },
  { id: 'sage',     name: '鼠尾草', primary: '#5a675a' },
  { id: 'sky',      name: '天蓝',   primary: '#0284c7' },
  { id: 'charcoal', name: '炭灰',   primary: '#64748b' },
  { id: 'berry',    name: '浆果',   primary: '#9d174d' },
  { id: 'peach',    name: '蜜桃',   primary: '#ea580c' },
  { id: 'teal',     name: '青色',   primary: '#0d9488' },
  { id: 'indigo',   name: '靛青',   primary: '#4f46e5' },
  { id: 'monochrome',name:'黑白',   primary: '#374151' },
  { id: 'neon',     name: '霓虹',   primary: '#22d3ee' },
  { id: 'pastel',   name: '柔彩',   primary: '#a78bfa' },
])

/* ===== 风格=调色板映射辅助色 ===== */
export const STYLE_SWATCH_COLORS: Record<string, string> = Object.freeze({
  swiss: '#DA291C', neubrutalism: '#FF6B35', webbrutalism: '#C0C0C0',
  skeuomorphism: '#8B6914', neumorphism: '#E0E0E0', glassmorphism: 'rgba(255,255,255,0.3)',
  flat20: '#4A90D9', material: '#6200EE', minimalism: '#F5F5F5', maximalism: '#FF0055',
  vaporwave: '#FF71CE', y2k: '#00C2FF', darkmode: '#121212',
  bauhaus: '#E30613', memphis: '#FF6600', claymorphism: '#FFB347',
  organic: '#7CB342', acid: '#00FF41', cyberpunk: '#FF006E', pixel: '#306230',
})

/* ===== 所有设计风格定义 ===== */
export const STYLES: readonly Style[] = Object.freeze([
  {
    id: 'swiss', name: '瑞士平面设计', short: 'Swiss',
    css: {
      '--stl-radius': '0px',
      '--stl-border-width': '2px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': 'Helvetica,"Helvetica Neue",Arial,sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '-0.02em',
      '--stl-line-height': '1.6',
      '--stl-shadow': 'none',
      '--stl-chip-style': 'outline',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '3px solid var(--pal-text-main)',
      '--stl-decoration': 'grid',
    },
    injectCSS: null,
  },
  {
    id: 'neubrutalism', name: '新丑主义', short: 'Neubrut',
    css: {
      '--stl-radius': '0px',
      '--stl-border-width': '3px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '"Arial Black","Impact",sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0',
      '--stl-line-height': '1.3',
      '--stl-shadow': '8px 8px 0px rgba(0,0,0,0.3)',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '4px solid var(--pal-text-main)',
      '--stl-decoration': 'none',
    },
    injectCSS: null,
  },
  {
    id: 'webbrutalism', name: '野兽主义', short: 'Brutal',
    css: {
      '--stl-radius': '0px',
      '--stl-border-width': '2px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '"Times New Roman",Times,Georgia,serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0',
      '--stl-line-height': '1.4',
      '--stl-shadow': 'none',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '3px solid #00f',
      '--stl-decoration': 'none',
    },
    injectCSS: '.header{font-family:"Times New Roman",serif}a{color:#00f;text-decoration:underline}',
  },
  {
    id: 'skeuomorphism', name: '拟物化主义', short: 'Skeuo',
    css: {
      '--stl-radius': '8px',
      '--stl-border-width': '1px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '"Georgia","Palatino",serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0.01em',
      '--stl-line-height': '1.5',
      '--stl-shadow': 'inset 0 2px 4px rgba(0,0,0,0.1),0 4px 8px rgba(0,0,0,0.15)',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '2px solid var(--pal-text-main)',
      '--stl-decoration': 'none',
    },
    injectCSS: null,
  },
  {
    id: 'neumorphism', name: '新拟物主义', short: 'Neumo',
    css: {
      '--stl-radius': '16px',
      '--stl-border-width': '0px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '-apple-system,sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0',
      '--stl-line-height': '1.5',
      '--stl-shadow': '9px 9px 16px rgba(0,0,0,0.08),-9px -9px 16px rgba(255,255,255,0.7)',
      '--stl-chip-style': 'neumo',
      '--stl-btn-style': 'neumo',
      '--stl-header-border': 'none',
      '--stl-decoration': 'none',
    },
    injectCSS: null,
  },
  {
    id: 'glassmorphism', name: '玻璃拟态主义', short: 'Glass',
    css: {
      '--stl-radius': '12px',
      '--stl-border-width': '1px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0',
      '--stl-line-height': '1.5',
      '--stl-shadow': '0 8px 32px rgba(0,0,0,0.1)',
      '--stl-chip-style': 'glass',
      '--stl-btn-style': 'glass',
      '--stl-header-border': '1px solid rgba(255,255,255,0.3)',
      '--stl-decoration': 'none',
    },
    injectCSS: `[data-style="glassmorphism"] .section,[data-style="glassmorphism"] .header,[data-style="glassmorphism"] .avatar-panel{background:rgba(255,255,255,0.15)!important;backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);border:1px solid rgba(255,255,255,0.25)}[data-style="glassmorphism"] body{background:linear-gradient(135deg,#667eea,#764ba2)}[data-style="glassmorphism"] .avatar-trigger{background:rgba(255,255,255,0.1)!important;backdrop-filter:blur(8px)}[data-style="glassmorphism"] .palette-swatch{border-color:rgba(255,255,255,0.4)}[data-style="glassmorphism"] .chip{background:rgba(255,255,255,0.12)!important;backdrop-filter:blur(6px)}[data-style="glassmorphism"] .chip.active{background:rgba(255,255,255,0.3)!important}`,
  },
  {
    id: 'flat20', name: '扁平化 2.0', short: 'Flat 2',
    css: {
      '--stl-radius': '6px',
      '--stl-border-width': '1px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0',
      '--stl-line-height': '1.5',
      '--stl-shadow': '0 2px 8px rgba(0,0,0,0.08)',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '2px solid var(--pal-text-main)',
      '--stl-decoration': 'none',
    },
    injectCSS: null,
  },
  {
    id: 'material', name: '材料设计主义', short: 'Material',
    css: {
      '--stl-radius': '4px',
      '--stl-border-width': '0px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': 'Roboto,"Segoe UI",sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0.01em',
      '--stl-line-height': '1.5',
      '--stl-shadow': '0 2px 4px rgba(0,0,0,0.14),0 3px 8px rgba(0,0,0,0.12)',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'raised',
      '--stl-header-border': 'none',
      '--stl-decoration': 'elevation',
    },
    injectCSS: `[data-style="material"] .section{box-shadow:0 2px 4px -1px rgba(0,0,0,0.2),0 4px 5px 0 rgba(0,0,0,0.14),0 1px 10px 0 rgba(0,0,0,0.12)}[data-style="material"] .btn-submit{box-shadow:0 2px 4px -1px rgba(0,0,0,0.2),0 4px 5px 0 rgba(0,0,0,0.14),0 1px 10px 0 rgba(0,0,0,0.12);border-radius:4px}[data-style="material"] .chip:active{transform:scale(0.96)}`,
  },
  {
    id: 'minimalism', name: '极简主义', short: 'Minimal',
    css: {
      '--stl-radius': '0px',
      '--stl-border-width': '1px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0.05em',
      '--stl-line-height': '1.8',
      '--stl-shadow': 'none',
      '--stl-chip-style': 'outline',
      '--stl-btn-style': 'outline',
      '--stl-header-border': '1px solid var(--pal-text-main)',
      '--stl-decoration': 'none',
    },
    injectCSS: null,
  },
  {
    id: 'maximalism', name: '极复主义', short: 'Maximal',
    css: {
      '--stl-radius': '8px',
      '--stl-border-width': '2px',
      '--stl-border-style': 'double',
      '--stl-font-ui': '-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0.02em',
      '--stl-line-height': '1.5',
      '--stl-shadow': '0 4px 16px rgba(0,0,0,0.15)',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '3px double var(--pal-text-main)',
      '--stl-decoration': 'pattern',
    },
    injectCSS: `[data-style="maximalism"] .section{border:2px double var(--pal-border);background:repeating-linear-gradient(45deg,transparent,transparent 10px,var(--pal-primary-soft) 10px,var(--pal-primary-soft) 11px)}[data-style="maximalism"] .header{background:repeating-linear-gradient(-45deg,transparent,transparent 8px,var(--pal-primary-soft) 8px,var(--pal-primary-soft) 9px)}[data-style="maximalism"] .chip{border-width:2px;border-style:double}`,
  },
  {
    id: 'vaporwave', name: '蒸汽波主义', short: 'Vapor',
    css: {
      '--stl-radius': '0px',
      '--stl-border-width': '2px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '"Courier New",monospace',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0.1em',
      '--stl-line-height': '1.5',
      '--stl-shadow': '0 0 10px rgba(255,113,206,0.3)',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '2px solid #FF71CE',
      '--stl-decoration': 'grid',
    },
    injectCSS: `[data-style="vaporwave"] body{background:linear-gradient(180deg,#0a0a2e 0%,#1a0a3e 30%,#2a1a4e 60%,#ff71ce 100%)}[data-style="vaporwave"] .section,[data-style="vaporwave"] .header{background:rgba(10,10,46,0.85)!important;border:2px solid #FF71CE}[data-style="vaporwave"] .section-title{border-bottom-color:#FF71CE}[data-style="vaporwave"] .record{border-bottom-color:#FF71CE}[data-style="vaporwave"] .header h1{text-shadow:0 0 10px #FF71CE,0 0 20px #00DCFF}`,
  },
  {
    id: 'y2k', name: 'Y2K 千禧风', short: 'Y2K',
    css: {
      '--stl-radius': '999px',
      '--stl-border-width': '2px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '"Trebuchet MS","Arial",sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0.05em',
      '--stl-line-height': '1.5',
      '--stl-shadow': '0 0 0 2px rgba(0,194,255,0.2)',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '2px solid #00C2FF',
      '--stl-decoration': 'chrome',
    },
    injectCSS: `[data-style="y2k"] .section,[data-style="y2k"] .header{animation:y2k-bounce-in 0.4s ease-out both}[data-style="y2k"] .btn-submit{animation:y2k-float 3s ease-in-out infinite}`,
  },
  {
    id: 'darkmode', name: '暗黑模式', short: 'Dark',
    css: {
      '--stl-radius': '6px',
      '--stl-border-width': '1px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0',
      '--stl-line-height': '1.5',
      '--stl-shadow': '0 4px 12px rgba(0,0,0,0.3)',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '2px solid var(--pal-text-main)',
      '--stl-decoration': 'none',
    },
    injectCSS: `[data-style="darkmode"] body{background:#0d0d0d!important;color:#e0e0e0}[data-style="darkmode"] .section,[data-style="darkmode"] .header{background:#1a1a1a!important;border-color:#333}[data-style="darkmode"] .chip{background:#2a2a2a!important;color:#e0e0e0}[data-style="darkmode"] .form-control{background:#2a2a2a!important;color:#e0e0e0;border-color:#444}[data-style="darkmode"] .month-filter input{background:#2a2a2a!important;color:#e0e0e0;border-color:#444}`,
  },
  {
    id: 'bauhaus', name: '包豪斯主义', short: 'Bauhaus',
    css: {
      '--stl-radius': '0px',
      '--stl-border-width': '3px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '"Impact","Arial Black",sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0.02em',
      '--stl-line-height': '1.4',
      '--stl-shadow': 'none',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '4px solid var(--pal-text-main)',
      '--stl-decoration': 'geometric',
    },
    injectCSS: `[data-style="bauhaus"] .header h1{background:var(--pal-primary);color:#fff;padding:4px 12px}[data-style="bauhaus"] .section-title{background:var(--pal-primary);color:#fff;padding:4px 8px;border:none}[data-style="bauhaus"] .btn-submit{background:var(--pal-primary);border:3px solid var(--pal-text-main)}[data-style="bauhaus"] .chip.active{background:var(--pal-danger);border-color:var(--pal-text-main)}`,
  },
  {
    id: 'memphis', name: '孟菲斯主义', short: 'Memphis',
    css: {
      '--stl-radius': '4px',
      '--stl-border-width': '2px',
      '--stl-border-style': 'dotted',
      '--stl-font-ui': '-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0',
      '--stl-line-height': '1.5',
      '--stl-shadow': '4px 4px 0 rgba(0,0,0,0.1)',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '2px dotted var(--pal-text-main)',
      '--stl-decoration': 'polka',
    },
    injectCSS: `[data-style="memphis"] .section{background:var(--pal-surface);border:2px dotted var(--pal-border);position:relative}[data-style="memphis"] .section::before{content:"";position:absolute;top:8px;right:8px;width:12px;height:12px;background:var(--pal-primary);border-radius:50%;opacity:0.3}[data-style="memphis"] .section::after{content:"";position:absolute;bottom:8px;left:8px;width:8px;height:8px;background:var(--pal-danger);transform:rotate(45deg);opacity:0.3}[data-style="memphis"] .chip{border-style:dotted}`,
  },
  {
    id: 'claymorphism', name: '3D 粘土拟态', short: 'Clay',
    css: {
      '--stl-radius': '18px',
      '--stl-border-width': '0px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0',
      '--stl-line-height': '1.5',
      '--stl-shadow': '0 6px 12px rgba(0,0,0,0.1),0 12px 24px rgba(0,0,0,0.06)',
      '--stl-chip-style': 'clay',
      '--stl-btn-style': 'clay',
      '--stl-header-border': 'none',
      '--stl-decoration': 'none',
    },
    injectCSS: `[data-style="claymorphism"] .section,[data-style="claymorphism"] .header{border-radius:18px;background:linear-gradient(145deg,var(--pal-surface),var(--pal-surface-alt))!important}[data-style="claymorphism"] .chip{border-radius:14px;background:linear-gradient(145deg,var(--pal-surface-alt),var(--pal-surface))!important;box-shadow:0 4px 8px rgba(0,0,0,0.08)}[data-style="claymorphism"] .btn-submit{border-radius:14px;background:linear-gradient(145deg,var(--pal-text-main),#333)!important;box-shadow:0 4px 8px rgba(0,0,0,0.2)}`,
  },
  {
    id: 'organic', name: '有机自然主义', short: 'Organic',
    css: {
      '--stl-radius': '12px',
      '--stl-border-width': '1px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0',
      '--stl-line-height': '1.6',
      '--stl-shadow': '0 4px 12px rgba(124,179,66,0.15)',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '2px solid var(--pal-text-main)',
      '--stl-decoration': 'leaf',
    },
    injectCSS: `[data-style="organic"] body{background:linear-gradient(180deg,#f5faf0,#e8f5e0)}[data-style="organic"] .section{border-radius:12px;border:1px solid var(--pal-border)}[data-style="organic"] .chip{border-radius:999px}[data-style="organic"] .avatar-trigger{border-radius:999px}`,
  },
  {
    id: 'acid', name: '酸性视觉主义', short: 'Acid',
    css: {
      '--stl-radius': '0px',
      '--stl-border-width': '2px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '"Impact","Arial Black",sans-serif',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0.1em',
      '--stl-line-height': '1.3',
      '--stl-shadow': '0 0 20px rgba(0,255,65,0.3)',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '2px solid #00FF41',
      '--stl-decoration': 'glitch',
    },
    injectCSS: `[data-style="acid"] body{background:#0a0a0a!important}[data-style="acid"] .section{background:#111!important;border:2px solid #00FF41;box-shadow:0 0 15px rgba(0,255,65,0.2)}[data-style="acid"] .header{background:#111!important;border-color:#00FF41}[data-style="acid"] .header h1{color:#00FF41!important;text-shadow:0 0 10px #00FF41}[data-style="acid"] .section-title{color:#FF00FF!important}[data-style="acid"] .chip{border:2px solid #FF00FF;color:#FF00FF!important;background:transparent!important}[data-style="acid"] .chip.active{background:#FF00FF!important;color:#000!important}[data-style="acid"] .btn-submit{background:linear-gradient(90deg,#FF00FF,#00FF41)}[data-style="acid"] .stat-value{color:#FF00FF!important}`,
  },
  {
    id: 'cyberpunk', name: '赛博朋克主义', short: 'Cyber',
    css: {
      '--stl-radius': '0px',
      '--stl-border-width': '2px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '"Courier New",monospace',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0.05em',
      '--stl-line-height': '1.4',
      '--stl-shadow': '0 0 15px rgba(255,0,110,0.3)',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '2px solid #FF006E',
      '--stl-decoration': 'hud',
    },
    injectCSS: `[data-style="cyberpunk"] body{background:#0a0e1a!important}[data-style="cyberpunk"] .section{background:#0d1321!important;border:2px solid #FF006E;box-shadow:0 0 10px rgba(255,0,110,0.2),inset 0 0 10px rgba(0,245,255,0.05)}[data-style="cyberpunk"] .header{background:#0d1321!important;border-color:#FF006E}[data-style="cyberpunk"] .header h1{color:#00F5FF!important;text-shadow:0 0 10px #00F5FF,0 0 20px #00F5FF}[data-style="cyberpunk"] .section-title{color:#FF006E!important}[data-style="cyberpunk"] .chip{border:2px solid #00F5FF;color:#00F5FF!important;background:transparent!important}[data-style="cyberpunk"] .chip.active{background:#FF006E!important;border-color:#FF006E;color:#fff!important}[data-style="cyberpunk"] .stat-value{color:#00F5FF!important}[data-style="cyberpunk"] .record{border-bottom-color:#FF006E}[data-style="cyberpunk"] .record:hover{animation:glitch 0.3s ease-in-out}@keyframes glitch{0%{transform:translate(0)}20%{transform:translate(-2px,2px)}40%{transform:translate(2px,-1px)}60%{transform:translate(-1px,-2px)}80%{transform:translate(1px,1px)}100%{transform:translate(0)}}`,
  },
  {
    id: 'pixel', name: '复古像素主义', short: '8-Bit',
    css: {
      '--stl-radius': '0px',
      '--stl-border-width': '2px',
      '--stl-border-style': 'solid',
      '--stl-font-ui': '"Courier New","Lucida Console",monospace',
      '--stl-font-heading': 'var(--stl-font-ui)',
      '--stl-letter-spacing': '0',
      '--stl-line-height': '1.4',
      '--stl-shadow': 'none',
      '--stl-chip-style': 'solid',
      '--stl-btn-style': 'solid',
      '--stl-header-border': '4px solid var(--pal-text-main)',
      '--stl-decoration': 'pixel',
    },
    injectCSS: `[data-style="pixel"] .section{border:4px solid var(--pal-border);image-rendering:pixelated}[data-style="pixel"] .header{border:4px solid var(--pal-text-main)}[data-style="pixel"] .chip{border:3px solid var(--pal-border)}[data-style="pixel"] .chip.active{background:var(--pal-primary);border-color:var(--pal-text-main)}[data-style="pixel"] .btn-submit{border:3px solid var(--pal-text-main);box-shadow:4px 4px 0 var(--pal-text-main)}[data-style="pixel"] ::selection{background:var(--pal-primary);color:#fff}`,
  },
])

/* ===== Storage Keys ===== */
export const STORE_KEY = 'swiss_expenses_pro_v4'
export const BUDGET_KEY = 'swiss_expenses_budgets_v1'
export const PALETTE_STORE_KEY = 'swiss_expenses_palette'
export const STYLE_STORE_KEY = 'swiss_expenses_style'
export const AVATAR_STORE_KEY = 'swiss_expenses_avatar'
export const GUIDE_STORE_KEY = 'swiss_expenses_guide'
export const TAGS_KEY = 'swiss_expenses_tags'
export const SUB_CATEGORY_KEY = 'swiss_expenses_subcats'